// Australian English 5-letter words database
// Based on Macquarie Dictionary standards with proper Australian spelling

// Words that can be the daily answer (more common, well-known words)
const ANSWER_WORDS = [
    // Common Australian words
    'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
    'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alien', 'align', 'alike', 'alive',
    'allow', 'alone', 'along', 'alter', 'amber', 'amend', 'among', 'anger', 'angle', 'angry',
    'apart', 'apple', 'apply', 'arena', 'argue', 'arise', 'array', 'arrow', 'aside', 'asset',
    'atlas', 'audio', 'audit', 'avoid', 'awake', 'award', 'aware', 'badly', 'baker', 'basic',
    'batch', 'beach', 'beard', 'beast', 'being', 'belly', 'below', 'bench', 'billy', 'birth',
    'black', 'blade', 'blame', 'blank', 'blast', 'blaze', 'bleak', 'blend', 'bless', 'blind',
    'block', 'blood', 'bloom', 'blown', 'blues', 'bluff', 'blunt', 'blush', 'board', 'boast',
    'bobby', 'boost', 'booth', 'bound', 'boxer', 'brain', 'brake', 'brand', 'brass', 'brave',
    'bread', 'break', 'breed', 'bride', 'brief', 'bring', 'brink', 'broad', 'broke', 'brook',
    'brown', 'brush', 'buddy', 'build', 'built', 'bunch', 'bunny', 'burnt', 'burst', 'buyer',
    
    // Australian-specific terms with proper spelling
    'arsey', 'bogan', 'booze', 'budge', 'chook', 'cobba', 'cooee', 'cuppa', 'dingo', 'drongo',
    'dunny', 'esky', 'fair', 'footy', 'garbo', 'giddy', 'gumby', 'heaps', 'jacky', 'joey',
    'kelly', 'larks', 'mate', 'mucko', 'nifty', 'ocker', 'outie', 'polly', 'pub', 'ripper',
    'scrub', 'seppo', 'sheila', 'snag', 'swag', 'tinny', 'tucker', 'ute', 'wowee', 'yakka',
    
    // More standard words with Australian spelling preferences
    'cable', 'cache', 'cadet', 'camp', 'canal', 'candy', 'canoe', 'cargo', 'carry', 'carve',
    'catch', 'cause', 'chain', 'chair', 'chalk', 'champ', 'chaos', 'chard', 'charm', 'chart',
    'chase', 'cheap', 'cheat', 'check', 'cheek', 'chess', 'chest', 'chick', 'chief', 'child',
    'china', 'choir', 'chord', 'chose', 'chunk', 'churn', 'chute', 'cider', 'cigar', 'cinch',
    'circa', 'civic', 'civil', 'clamp', 'clang', 'clank', 'clash', 'class', 'clean', 'clear',
    'clerk', 'click', 'cliff', 'climb', 'cling', 'cloak', 'clock', 'clone', 'close', 'cloth',
    'cloud', 'clown', 'clubs', 'cluck', 'clued', 'clump', 'clung', 'coach', 'coast', 'cocoa',
    'coded', 'coder', 'codes', 'colon', 'combo', 'comic', 'conch', 'coral', 'corps', 'couch',
    'cough', 'could', 'count', 'court', 'cover', 'crack', 'craft', 'cramp', 'crane', 'crash',
    'crazy', 'cream', 'creek', 'creep', 'cress', 'crisp', 'croak', 'crock', 'crook', 'cross',
    'crowd', 'crown', 'crude', 'cruel', 'crumb', 'crush', 'crypt', 'cubic', 'cumin', 'curry',
    
    // More words ensuring good mix
    'daisy', 'dance', 'dandy', 'dared', 'dated', 'dealt', 'death', 'debit', 'debug', 'decal',
    'decor', 'decoy', 'deed', 'delay', 'delta', 'delve', 'demon', 'dense', 'depot', 'depth',
    'derby', 'desk', 'devil', 'diary', 'dice', 'died', 'diet', 'digit', 'dimly', 'diner',
    'dirty', 'disco', 'ditch', 'ditto', 'diver', 'dizzy', 'dock', 'dodge', 'doing', 'dolly',
    'donor', 'donut', 'doubt', 'dough', 'dove', 'down', 'dozen', 'draft', 'drag', 'drain',
    'drake', 'drama', 'drank', 'drape', 'drawl', 'drawn', 'dread', 'dream', 'dress', 'dried',
    'drill', 'drink', 'drive', 'droit', 'drone', 'drool', 'drop', 'drove', 'drown', 'drugs',
    'drunk', 'dryer', 'ducks', 'dully', 'dummy', 'dump', 'dunes', 'dusty', 'dutch', 'dwarf',
    'dwell', 'dying'
];

// All valid 5-letter words for guess validation (includes answers + additional valid words)
const VALID_WORDS = [
    ...ANSWER_WORDS,
    
    // Common English words that should definitely be valid
    'badge', 'badly', 'bagel', 'baker', 'balls', 'bands', 'banjo', 'banks', 'barks', 'barns',
    'basic', 'batch', 'baths', 'beach', 'beads', 'beans', 'bears', 'beats', 'beers', 'bells',
    'bench', 'bends', 'bikes', 'bills', 'binds', 'birds', 'birth', 'black', 'blade', 'blame',
    'bland', 'blank', 'blast', 'blaze', 'bleak', 'blend', 'bless', 'blind', 'blink', 'bliss',
    'block', 'blood', 'bloom', 'blown', 'blues', 'blunt', 'blush', 'board', 'boast', 'boats',
    'bobby', 'bonds', 'bones', 'bonus', 'books', 'boost', 'booth', 'boots', 'bound', 'boxed',
    'boxer', 'boxes', 'brain', 'brake', 'brand', 'brass', 'brave', 'bread', 'break', 'breed',
    'brick', 'bride', 'brief', 'bring', 'brink', 'broad', 'broke', 'brook', 'brown', 'brush',
    'buddy', 'build', 'built', 'bulbs', 'bulls', 'bunch', 'bunny', 'burnt', 'burst', 'buses',
    
    // C words - MASSIVELY EXPANDED
    'cabal', 'cabby', 'caber', 'cabin', 'cable', 'cacao', 'cache', 'caddy', 'cadet', 'cadge',
    'cafes', 'caged', 'cager', 'cages', 'cagey', 'cairn', 'caked', 'cakes', 'cakey', 'calls',
    'calms', 'calve', 'calyx', 'camel', 'cameo', 'camps', 'campy', 'canal', 'candy', 'caned',
    'caner', 'canes', 'canid', 'canny', 'canoe', 'canon', 'canso', 'canst', 'canto', 'cants',
    'caped', 'caper', 'capes', 'capon', 'capos', 'caput', 'carat', 'carbo', 'carbs', 'cards',
    'cared', 'carer', 'cares', 'cargo', 'carks', 'carle', 'carls', 'carns', 'carob', 'carol',
    'carom', 'carps', 'carry', 'carse', 'carte', 'carts', 'carve', 'carvy', 'cased', 'cases',
    'casks', 'casky', 'caste', 'casts', 'catch', 'cater', 'cates', 'catty', 'cauks', 'cauls',
    'cause', 'caved', 'caver', 'caves', 'cavie', 'cavil', 'cawed', 'cease', 'cecal', 'cedar',
    'ceded', 'ceder', 'cedes', 'ceiba', 'ceils', 'cells', 'celts', 'cense', 'cento', 'cents',
    'centu', 'cerci', 'cered', 'ceres', 'ceria', 'ceric', 'ceros', 'certs', 'cesar', 'cesta',
    'cesti', 'cetes', 'chace', 'chack', 'chads', 'chafe', 'chaff', 'chain', 'chair', 'chais',
    'chalk', 'champ', 'chams', 'chane', 'chang', 'chank', 'chant', 'chaos', 'chape', 'chaps',
    'chard', 'chare', 'chark', 'charm', 'charr', 'chars', 'chart', 'chary', 'chase', 'chasm',
    'chats', 'chave', 'chawk', 'chaws', 'chaya', 'chays', 'cheap', 'cheat', 'check', 'cheek',
    'cheep', 'cheer', 'chefs', 'chela', 'chemo', 'chems', 'chere', 'chert', 'chess', 'chest',
    'cheth', 'chevy', 'chews', 'chewy', 'chiao', 'chias', 'chiba', 'chick', 'chico', 'chics',
    'chide', 'chief', 'chiel', 'chiff', 'child', 'chile', 'chili', 'chill', 'chimb', 'chime',
    'chimp', 'china', 'chine', 'ching', 'chink', 'chino', 'chins', 'chips', 'chirk', 'chirm',
    'chirp', 'chirr', 'chits', 'chive', 'chivy', 'chizz', 'chock', 'chode', 'chogs', 'choil',
    'choir', 'choke', 'choky', 'chomp', 'chons', 'choof', 'chook', 'choom', 'choon', 'chops',
    'chord', 'chore', 'chose', 'chota', 'chott', 'chout', 'choux', 'chown', 'chows', 'chubs',
    'chuck', 'chufa', 'chuff', 'chugs', 'chump', 'chums', 'chunk', 'churl', 'churn', 'churr',
    'chuse', 'chute', 'chuts', 'chyle', 'chyme', 'ciaos', 'cibol', 'cider', 'ciels', 'cigar',
    'ciggy', 'cilia', 'cills', 'cimar', 'cinch', 'cinct', 'cines', 'cinqs', 'cions', 'circa',
    'circs', 'cires', 'cirls', 'cirri', 'cisco', 'cissy', 'cists', 'cited', 'citer', 'cites',
    'civet', 'civic', 'civie', 'civil', 'civvy', 'clach', 'clack', 'clade', 'clads', 'claes',
    'clags', 'claim', 'clam', 'clamp', 'clams', 'clang', 'clank', 'clans', 'claps', 'clapt',
    'claro', 'clart', 'clary', 'clash', 'clasp', 'class', 'clast', 'clats', 'claut', 'clave',
    'clavi', 'claws', 'clays', 'clean', 'clear', 'cleat', 'cleck', 'cleek', 'cleep', 'clefs',
    'cleft', 'clegs', 'cleik', 'clems', 'clepe', 'clept', 'clerk', 'cleve', 'clews', 'click',
    'cliff', 'clift', 'climb', 'clime', 'cline', 'cling', 'clink', 'clint', 'clipe', 'clips',
    'clipt', 'clits', 'cloak', 'cloam', 'clock', 'clod', 'clogs', 'clomb', 'clomp', 'clone',
    'clonk', 'clons', 'cloop', 'cloot', 'clops', 'close', 'clote', 'cloth', 'clots', 'cloud',
    'clour', 'clous', 'clout', 'clown', 'cloys', 'cloze', 'clubs', 'cluck', 'clued', 'clues',
    'cluey', 'clump', 'clung', 'clunk', 'clupe', 'clure', 'cluse', 'clype', 'cnida', 'coach',
    'coact', 'coady', 'coals', 'coaly', 'coapt', 'coast', 'coate', 'coati', 'coats', 'cobbs',
    'cobby', 'cobia', 'coble', 'cobra', 'cobza', 'cocas', 'cocci', 'cocco', 'cocks', 'cocky',
    'cocoa', 'cocos', 'codas', 'codec', 'coded', 'coder', 'codes', 'codex', 'codon', 'coeds',
    'coffs', 'cogie', 'cogon', 'cogue', 'cohab', 'cohen', 'cohoe', 'cohos', 'coign', 'coils',
    'coins', 'coirs', 'coits', 'coked', 'cokes', 'colas', 'colby', 'colds', 'coled', 'coles',
    'colic', 'colin', 'colls', 'colly', 'colog', 'colon', 'color', 'colts', 'colza', 'comae',
    'comal', 'comas', 'combe', 'combi', 'combo', 'combs', 'comby', 'comer', 'comes', 'comet',
    'comfy', 'comic', 'comix', 'comma', 'commo', 'comms', 'commy', 'compo', 'comps', 'compt',
    'comte', 'comus', 'conch', 'condo', 'coned', 'cones', 'coney', 'confs', 'conga', 'conge',
    'congo', 'conic', 'conin', 'conks', 'conky', 'conne', 'conns', 'conte', 'conto', 'conus',
    'cooch', 'cooed', 'cooee', 'cooer', 'cooey', 'cooks', 'cooky', 'cools', 'cooly', 'coomb',
    'cooms', 'coomy', 'coons', 'coops', 'coopt', 'coost', 'coots', 'copal', 'copay', 'coped',
    'copen', 'coper', 'copes', 'cophs', 'copia', 'copis', 'coppy', 'copra', 'copse', 'copsy',
    'coral', 'corbe', 'corby', 'cords', 'cored', 'corer', 'cores', 'corgi', 'coria', 'corks',
    'corky', 'corms', 'corns', 'cornu', 'corny', 'corps', 'corse', 'corso', 'cosec', 'coses',
    'coset', 'cosey', 'cosie', 'costa', 'costs', 'cotan', 'coted', 'cotes', 'coths', 'cotta',
    'cotts', 'couch', 'coude', 'cough', 'could', 'count', 'coupe', 'coups', 'courb', 'courd',
    'coure', 'cours', 'court', 'couta', 'couth', 'coved', 'coven', 'cover', 'coves', 'covet',
    'covey', 'covin', 'cowal', 'cowan', 'cowed', 'cower', 'cowks', 'cowls', 'cowry', 'coxae',
    'coxal', 'coxed', 'coxes', 'coypu', 'coypu', 'cozen', 'cozes', 'cozey', 'cozie', 'crabs',
    'crack', 'craft', 'crags', 'craic', 'craig', 'crake', 'cramp', 'crams', 'crane', 'crank',
    'crans', 'crape', 'craps', 'crapy', 'crare', 'crash', 'crass', 'crate', 'crave', 'crawl',
    'craws', 'craze', 'crazy', 'creak', 'cream', 'creat', 'creds', 'creed', 'creek', 'creel',
    'creep', 'crees', 'creme', 'crems', 'crena', 'crepe', 'creps', 'crept', 'cress', 'crest',
    'crewe', 'crews', 'crias', 'cribs', 'crick', 'cried', 'crier', 'cries', 'crime', 'crimp',
    'crims', 'crine', 'crink', 'crins', 'cripe', 'crisp', 'criss', 'crith', 'crits', 'croak',
    'croci', 'crock', 'crocs', 'croft', 'crogs', 'crone', 'cronk', 'crony', 'crook', 'crool',
    'croom', 'croon', 'crops', 'crore', 'cross', 'crost', 'croup', 'crout', 'crowd', 'crown',
    'crows', 'croze', 'cruck', 'crude', 'cruds', 'crudy', 'cruel', 'cruet', 'cruft', 'crumb',
    'crums', 'crunk', 'crura', 'cruse', 'crush', 'crust', 'crusy', 'cruve', 'crwth', 'crypt',
    'ctene', 'cubed', 'cuber', 'cubes', 'cubic', 'cubit', 'cuddy', 'cuds', 'cuffs', 'cuifs',
    'cuing', 'cuish', 'cuits', 'cukes', 'culch', 'culet', 'culex', 'culls', 'cully', 'culms',
    'culpa', 'culti', 'cults', 'culty', 'cumber', 'cumin', 'cummer', 'cumul', 'cunei', 'cunit',
    'cunts', 'cupel', 'cupid', 'cuppa', 'cuppy', 'curbs', 'curds', 'curdy', 'cured', 'curer',
    'cures', 'curfs', 'curia', 'curie', 'curio', 'curli', 'curls', 'curly', 'curns', 'curny',
    'currs', 'curry', 'curse', 'cursi', 'curst', 'curve', 'curvy', 'cusec', 'cushy', 'cusks',
    'cusps', 'cuspy', 'cussy', 'cutch', 'cuter', 'cutes', 'cutey', 'cutie', 'cutin', 'cutis',
    'cutto', 'cutty', 'cutup', 'cuvee', 'cuzes', 'cwtch', 'cyano', 'cyans', 'cyber', 'cycad',
    'cycas', 'cycle', 'cyclo', 'cyder', 'cylix', 'cymae', 'cymar', 'cymas', 'cymes', 'cynic',
    'cysts', 'cytes', 'cyton', 'czars',
    
    // D words  
    'daily', 'daisy', 'dance', 'dandy', 'dared', 'dates', 'dealt', 'death', 'debit', 'decal',
    'decor', 'decoy', 'deeds', 'delay', 'delta', 'delve', 'demon', 'dense', 'depot', 'depth',
    'derby', 'desks', 'devil', 'diary', 'diced', 'diets', 'digit', 'dimly', 'diner', 'dirty',
    'disco', 'ditch', 'ditto', 'diver', 'dizzy', 'docks', 'dodge', 'doing', 'dolly', 'donor',
    'donut', 'doors', 'doubt', 'dough', 'doves', 'downs', 'dozen', 'draft', 'drags', 'drain',
    'drake', 'drama', 'drank', 'drape', 'drawl', 'drawn', 'dread', 'dream', 'dress', 'dried',
    'drill', 'drink', 'drive', 'drone', 'drool', 'drops', 'drove', 'drown', 'drugs', 'drunk',
    'ducks', 'dully', 'dummy', 'dumps', 'dunes', 'dusty', 'dutch', 'dwarf', 'dwell', 'dying',
    
    // E words
    'eager', 'eagle', 'early', 'earth', 'easel', 'eaten', 'eater', 'ebbed', 'ebony', 'ebook',
    'eclat', 'edema', 'edged', 'edges', 'edict', 'edify', 'edits', 'eight', 'eject', 'elbow',
    'elder', 'elect', 'elegy', 'elfin', 'elide', 'elite', 'elope', 'elude', 'elver', 'elves',
    'email', 'embed', 'ember', 'emcee', 'emend', 'emery', 'emits', 'emoji', 'emote', 'empty',
    'enact', 'ended', 'endow', 'enemy', 'enjoy', 'enter', 'entry', 'envoy', 'equal', 'equip',
    'erase', 'erect', 'error', 'erupt', 'essay', 'ester', 'ether', 'ethic', 'ethos', 'ethyl',
    'etude', 'euros', 'evert', 'every', 'evict', 'evils', 'exact', 'exalt', 'exams', 'excel',
    'exile', 'exist', 'exits', 'expat', 'expel', 'extra', 'exude', 'eyass', 'eying',
    
    // F words - MASSIVELY EXPANDED
    'fable', 'faced', 'facer', 'faces', 'facet', 'facia', 'facts', 'faddy', 'faded', 'fader',
    'fades', 'fadge', 'fados', 'faena', 'faery', 'faffs', 'fagot', 'faiks', 'fails', 'faine',
    'fains', 'faint', 'fairs', 'fairy', 'faith', 'fajita', 'faked', 'faker', 'fakes', 'fakir',
    'falaj', 'falls', 'false', 'famed', 'fames', 'fancy', 'fands', 'fanes', 'fanga', 'fangs',
    'fanks', 'fanny', 'fanon', 'fanos', 'fanum', 'faqir', 'farad', 'farce', 'farci', 'farcy',
    'fards', 'fared', 'farer', 'fares', 'farle', 'farls', 'farms', 'faros', 'farro', 'farse',
    'farts', 'fasci', 'fasti', 'fasts', 'fatal', 'fated', 'fates', 'fatly', 'fatso', 'fatty',
    'fatwa', 'faugh', 'fauld', 'fault', 'fauna', 'fauns', 'faurd', 'favas', 'favel', 'faver',
    'faves', 'favor', 'favus', 'fawns', 'fawny', 'faxed', 'faxes', 'fayed', 'fayne', 'fayre',
    'fazed', 'fazer', 'fazes', 'feal', 'fears', 'feart', 'fease', 'feast', 'feats', 'fecal',
    'feces', 'fecht', 'fecit', 'fecks', 'fedex', 'feds', 'feeds', 'feels', 'feems', 'feens',
    'feers', 'feese', 'feet', 'feeze', 'fehme', 'feint', 'feist', 'felch', 'fells', 'felly',
    'felon', 'felts', 'felty', 'femes', 'femme', 'femmy', 'femur', 'fence', 'fends', 'fenny',
    'fents', 'feods', 'feoff', 'feral', 'feres', 'feria', 'ferly', 'fermi', 'ferns', 'ferny',
    'ferry', 'fesse', 'festa', 'fests', 'fetal', 'fetas', 'fetch', 'feted', 'fetes', 'fetid',
    'fetor', 'fetta', 'fetts', 'fetus', 'feuar', 'feuds', 'feued', 'fever', 'fewer', 'feyed',
    'feyer', 'feyly', 'fezes', 'fezzy', 'fiado', 'fiar', 'fiars', 'fiats', 'fiber', 'fibre',
    'fibro', 'fibs', 'fices', 'fiche', 'fichu', 'ficin', 'ficos', 'ficus', 'fidge', 'fido',
    'fidos', 'fiefs', 'field', 'fiend', 'fient', 'fiere', 'fiers', 'fiery', 'fifed', 'fifer',
    'fifes', 'fifis', 'fifth', 'fifty', 'fight', 'figma', 'figos', 'fiked', 'fikes', 'filar',
    'filch', 'filed', 'filer', 'files', 'filet', 'fille', 'fillo', 'fills', 'filly', 'films',
    'filmy', 'filos', 'filth', 'filum', 'final', 'finca', 'finch', 'finds', 'fined', 'finer',
    'fines', 'finis', 'finks', 'finny', 'finos', 'fiord', 'fique', 'fired', 'firer', 'fires',
    'firie', 'firks', 'firms', 'firns', 'firry', 'first', 'firth', 'fiscs', 'fishy', 'fisks',
    'fists', 'fisty', 'fitch', 'fitly', 'fitna', 'fitte', 'fitts', 'fiver', 'fives', 'fixed',
    'fixer', 'fixes', 'fizzy', 'fjeld', 'fjord', 'flabs', 'flack', 'flaff', 'flags', 'flail',
    'flair', 'flak', 'flake', 'flaks', 'flaky', 'flame', 'flams', 'flamy', 'flane', 'flank',
    'flans', 'flaps', 'flare', 'flary', 'flash', 'flask', 'flats', 'flatt', 'flava', 'flawn',
    'flaws', 'flawy', 'flaxy', 'flays', 'flead', 'fleam', 'fleas', 'fleck', 'fleer', 'flees',
    'fleet', 'flegs', 'fleme', 'flesh', 'flews', 'fleys', 'flick', 'flics', 'flied', 'flier',
    'flies', 'flimp', 'flims', 'fling', 'flint', 'flips', 'flirs', 'flirt', 'flisk', 'flite',
    'flits', 'flitt', 'flive', 'float', 'flock', 'flocs', 'floes', 'flogs', 'flong', 'flood',
    'floor', 'flops', 'flora', 'flors', 'flory', 'flosh', 'floss', 'flota', 'flote', 'flour',
    'flout', 'flowe', 'flown', 'flows', 'flowy', 'fluds', 'flued', 'flues', 'fluff', 'fluid',
    'fluke', 'fluky', 'flume', 'flump', 'flung', 'flunk', 'fluor', 'flurr', 'flush', 'flute',
    'fluty', 'fluyt', 'flyby', 'flyer', 'flyes', 'flymo', 'flynn', 'flyup', 'foams', 'foamy',
    'focal', 'focus', 'foehn', 'fogas', 'fogey', 'foggy', 'fogie', 'fogle', 'fogou', 'fohns',
    'foids', 'foil', 'foins', 'foist', 'folds', 'foley', 'folia', 'folic', 'folie', 'folio',
    'folks', 'folky', 'folly', 'fomes', 'fonds', 'fondu', 'fonts', 'foods', 'foody', 'fools',
    'foots', 'footy', 'foram', 'foray', 'forby', 'force', 'fordo', 'fords', 'forel', 'fores',
    'forex', 'forge', 'forgo', 'forks', 'forky', 'forme', 'forms', 'forte', 'forth', 'forts',
    'forty', 'forum', 'forza', 'forze', 'fossa', 'fosse', 'fouat', 'fouds', 'fouer', 'fouet',
    'foule', 'fouls', 'found', 'fount', 'fours', 'fouth', 'fovea', 'fowls', 'fowth', 'foxed',
    'foxes', 'foyer', 'foyle', 'foyne', 'frabs', 'frack', 'fract', 'frags', 'frail', 'fraim',
    'frais', 'frame', 'franc', 'frank', 'frape', 'fraps', 'frass', 'frate', 'frati', 'frats',
    'fraud', 'fraus', 'frays', 'fraze', 'freak', 'frear', 'freax', 'freed', 'freer', 'frees',
    'freet', 'freir', 'frena', 'frend', 'freon', 'frere', 'fresh', 'fress', 'frets', 'fretz',
    'friar', 'fribs', 'fried', 'frier', 'fries', 'frigs', 'frijole', 'frill', 'frios', 'fripp',
    'frisk', 'frith', 'frits', 'fritt', 'fritz', 'frize', 'frizz', 'frock', 'froes', 'frogs',
    'frond', 'frons', 'front', 'frore', 'frosh', 'frost', 'froth', 'frown', 'frows', 'froze',
    'frugs', 'fruit', 'frump', 'frunk', 'frush', 'frust', 'fryer', 'fubar', 'fubby', 'fubsy',
    'fuchi', 'fuchs', 'fucks', 'fucus', 'fuddy', 'fudge', 'fudgy', 'fuels', 'fuero', 'fuffs',
    'fuffy', 'fugal', 'fuggy', 'fugie', 'fugio', 'fugue', 'fugus', 'fujis', 'fulah', 'fular',
    'fulls', 'fully', 'fultz', 'fumar', 'fumay', 'fumed', 'fumer', 'fumes', 'fumet', 'fundi',
    'funds', 'fundy', 'fungi', 'fungo', 'fungs', 'funks', 'funky', 'funny', 'furan', 'furca',
    'furls', 'furol', 'furor', 'furry', 'furth', 'furze', 'furzy', 'fused', 'fusee', 'fusel',
    'fuses', 'fusil', 'fuss', 'fussy', 'fusts', 'fusty', 'futon', 'fuzed', 'fuzee', 'fuzes',
    'fuzil', 'fuzzy', 'fyces', 'fyked', 'fykes', 'fyles', 'fylfot', 'fyrds', 'fytte',
    
    // G words
    'gains', 'games', 'gamma', 'gates', 'gears', 'genes', 'genre', 'ghost', 'giant', 'gifts',
    'girls', 'given', 'gives', 'glass', 'globe', 'glory', 'gloss', 'glove', 'glows', 'goals',
    'goats', 'going', 'goods', 'grace', 'grade', 'grain', 'grand', 'grant', 'grape', 'grasp',
    'grass', 'grave', 'great', 'greed', 'green', 'greet', 'grief', 'grill', 'grind', 'grins',
    'grips', 'gross', 'group', 'grove', 'grown', 'grows', 'gruel', 'grunt', 'guard', 'guess',
    'guest', 'guide', 'guild', 'guilt', 'guise', 'gulps', 'gunks', 'gusty',
    
    // H words  
    'habit', 'hairs', 'halls', 'hands', 'hangs', 'happy', 'hardy', 'harms', 'harsh', 'haste',
    'hasty', 'hatch', 'hated', 'hater', 'hates', 'hauls', 'haven', 'hawks', 'heads', 'heals',
    'hears', 'heart', 'heats', 'heavy', 'hedge', 'heels', 'helps', 'henry', 'herbs', 'hills',
    'hints', 'hired', 'hires', 'hobby', 'holds', 'holes', 'holly', 'homes', 'honey', 'honor',
    'hooks', 'hopes', 'horns', 'horse', 'hosts', 'hotel', 'hours', 'house', 'human', 'humor',
    'hurry', 'hurts', 'husky',
    
    // I words
    'icans', 'icons', 'ideal', 'ideas', 'idiot', 'image', 'imply', 'inbox', 'index', 'indie',
    'inner', 'input', 'irons', 'issue', 'items', 'ivory',
    
    // J words
    'jails', 'james', 'japan', 'jeans', 'jewel', 'jiffy', 'joins', 'joint', 'jokes', 'jones',
    'judge', 'juice', 'jumbo', 'jumps', 'jumpy', 'junes', 'junky', 'jurat',
    
    // K words
    'keeps', 'kicks', 'kills', 'kinds', 'kings', 'knife', 'knits', 'knock', 'knots', 'known',
    'knows',
    
    // L words
    'label', 'labor', 'lacks', 'lance', 'lands', 'lanes', 'large', 'laser', 'lasts', 'later',
    'laugh', 'layer', 'leads', 'leafs', 'learn', 'lease', 'least', 'leave', 'ledge', 'legal',
    'lemon', 'lends', 'level', 'lewis', 'light', 'liked', 'likes', 'limit', 'lined', 'lines',
    'links', 'lions', 'lists', 'lived', 'liver', 'lives', 'loads', 'loans', 'local', 'locks',
    'lodge', 'logic', 'logos', 'looks', 'loops', 'loose', 'lords', 'loses', 'loved', 'lover',
    'loves', 'lower', 'lucky', 'lunch', 'lungs', 'lying',
    
    // M words
    'macro', 'magic', 'major', 'maker', 'makes', 'males', 'malls', 'mange', 'maple', 'march',
    'marks', 'marry', 'marsh', 'mason', 'match', 'mates', 'maths', 'maybe', 'mayor', 'meals',
    'means', 'meant', 'meats', 'medal', 'media', 'meets', 'melon', 'melts', 'memos', 'menus',
    'mercy', 'merge', 'merit', 'merry', 'metal', 'meter', 'metro', 'mice', 'might', 'miles',
    'minds', 'mines', 'minor', 'mints', 'minus', 'mixed', 'mixer', 'mixes', 'modal', 'model',
    'modes', 'money', 'monks', 'month', 'moods', 'moral', 'moths', 'motor', 'mount', 'mouse',
    'mouth', 'moved', 'mover', 'moves', 'movie', 'mowed', 'mower', 'muddy', 'multi', 'music',
    
    // N words
    'named', 'names', 'nasty', 'naval', 'needs', 'nerve', 'never', 'newer', 'newly', 'night',
    'nine', 'nodes', 'noise', 'noisy', 'north', 'noted', 'notes', 'novel', 'nurse',
    
    // O words
    'oaths', 'ocean', 'odds', 'offer', 'often', 'older', 'olive', 'omega', 'onion', 'opens',
    'opera', 'order', 'organ', 'other', 'ought', 'ounce', 'outer', 'owned', 'owner',
    
    // P words
    'paced', 'packs', 'pages', 'pains', 'paint', 'pairs', 'panel', 'panic', 'pants', 'paper',
    'parks', 'parts', 'party', 'pasta', 'paste', 'patch', 'paths', 'pause', 'peace', 'peach',
    'peaks', 'pearl', 'pedal', 'penny', 'perks', 'phase', 'phone', 'photo', 'piano', 'picks',
    'piece', 'piles', 'pills', 'pilot', 'pinch', 'pines', 'pipes', 'pitch', 'pixel', 'pizza',
    'place', 'plain', 'plane', 'plank', 'plans', 'plant', 'plate', 'plays', 'plaza', 'plots',
    'plugs', 'poems', 'poets', 'point', 'poker', 'poles', 'polls', 'pools', 'pound', 'power',
    'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'props', 'proud',
    'prove', 'proxy', 'pulls', 'pulse', 'pumps', 'punch', 'pupil', 'purse', 'pushy', 'putty',
    
    // Q words
    'quack', 'quad', 'quail', 'quake', 'qualm', 'quart', 'queen', 'query', 'quest', 'queue',
    'quick', 'quiet', 'quill', 'quilt', 'quite', 'quota', 'quote',
    
    // R words - MASSIVELY EXPANDED INCLUDING RIDGE AND RIFLE!
    'rabat', 'rabbi', 'rabic', 'rabid', 'raced', 'racer', 'races', 'rache', 'racks', 'racon',
    'radar', 'radge', 'radio', 'radix', 'radon', 'raffs', 'rafts', 'ragas', 'ragde', 'raged',
    'ragee', 'rager', 'rages', 'ragga', 'raggs', 'raggy', 'ragis', 'ragus', 'rahed', 'raias',
    'raids', 'raiks', 'rails', 'rains', 'rainy', 'raird', 'raise', 'raita', 'raits', 'rajah',
    'rajas', 'rajes', 'raked', 'rakee', 'raker', 'rakes', 'rakis', 'rakus', 'rales', 'ralli',
    'rally', 'ralph', 'ramal', 'raman', 'ramas', 'rambo', 'ramee', 'ramet', 'ramie', 'ramin',
    'ramis', 'rammy', 'ramps', 'ramus', 'ranas', 'rance', 'ranch', 'rands', 'randy', 'ranee',
    'ranes', 'range', 'rangi', 'rangs', 'rangy', 'ranid', 'ranis', 'ranks', 'rants', 'raped',
    'raper', 'rapes', 'raphe', 'rapid', 'rappa', 'rared', 'raree', 'rarer', 'rares', 'rarks',
    'rased', 'raser', 'rases', 'rasps', 'raspy', 'rasse', 'rasta', 'ratal', 'ratan', 'ratas',
    'ratch', 'rated', 'ratel', 'rater', 'rates', 'ratha', 'rathe', 'raths', 'ratio', 'ratoo',
    'ratos', 'rattan', 'ratty', 'ratus', 'rauca', 'rauls', 'rauns', 'raved', 'ravel', 'raven',
    'raver', 'raves', 'rawer', 'rawin', 'rawly', 'rawns', 'raxed', 'raxes', 'rayah', 'rayas',
    'rayed', 'rayle', 'rayne', 'razed', 'razee', 'razer', 'razes', 'razoo', 'razor', 'reach',
    'react', 'readd', 'reads', 'ready', 'reaks', 'realm', 'realo', 'reals', 'reams', 'reamy',
    'reaps', 'rearm', 'rears', 'reask', 'reast', 'reata', 'reate', 'reave', 'rebbe', 'rebec',
    'rebel', 'rebid', 'rebit', 'rebop', 'rebus', 'rebut', 'rebuy', 'recal', 'recap', 'recce',
    'recco', 'reccy', 'recit', 'recks', 'recon', 'recta', 'recti', 'recto', 'recur', 'recut',
    'redds', 'reddy', 'reded', 'redes', 'redia', 'redid', 'redip', 'redly', 'redon', 'redos',
    'redox', 'redry', 'redub', 'redux', 'redye', 'reech', 'reede', 'reeds', 'reedy', 'reefs',
    'reefy', 'reeks', 'reeky', 'reels', 'reens', 'reest', 'reeve', 'refed', 'refel', 'refer',
    'reffo', 'refis', 'refit', 'refix', 'refly', 'refry', 'regar', 'reges', 'reggo', 'regia',
    'regin', 'regma', 'regna', 'regos', 'regur', 'rehem', 'reifs', 'reify', 'reign', 'reiks',
    'reink', 'reins', 'reird', 'reist', 'reits', 'rejig', 'rejon', 'reked', 'rekes', 'rekey',
    'relax', 'relay', 'relet', 'relic', 'relie', 'relit', 'rello', 'reman', 'remap', 'remex',
    'remid', 'remit', 'remix', 'remop', 'renal', 'rends', 'renew', 'renga', 'renig', 'renin',
    'renne', 'renos', 'rente', 'rents', 'reoil', 'reorg', 'repag', 'repay', 'repeg', 'repel',
    'repin', 'repit', 'repla', 'repot', 'repps', 'repro', 'reran', 'rerig', 'rerun', 'resay',
    'resaw', 'resay', 'resid', 'resin', 'resit', 'resod', 'resow', 'rest', 'rests', 'resty',
    'resus', 'retag', 'retax', 'retch', 'retem', 'retia', 'retie', 'retox', 'retro', 'retry',
    'reune', 'reups', 'reuse', 'reval', 'revco', 'revel', 'revet', 'revie', 'rewan', 'rewax',
    'rewed', 'rewet', 'rewin', 'rewon', 'rewth', 'rexes', 'rexis', 'reyed', 'reyes', 'reyne',
    'reyns', 'rezone', 'rheas', 'rheme', 'rhies', 'rhime', 'rhine', 'rhino', 'rhody', 'rhomb',
    'rhone', 'rhumb', 'rhyme', 'rhynd', 'rhyne', 'riads', 'rials', 'riant', 'riata', 'ribas',
    'ribby', 'ribes', 'riced', 'ricer', 'rices', 'ricey', 'richt', 'ricin', 'ricks', 'rider',
    'rides', 'ridge', 'ridgy', 'riems', 'rieve', 'rifer', 'riffs', 'rifte', 'rifts', 'right',
    'rigid', 'rigor', 'riled', 'riles', 'riley', 'rille', 'rills', 'rimae', 'rimal', 'rimed',
    'rimer', 'rimes', 'rimus', 'rinds', 'rindy', 'rines', 'rings', 'rinks', 'rinse', 'rioja',
    'riots', 'riped', 'ripen', 'riper', 'ripes', 'ripps', 'risen', 'riser', 'rises', 'rishi',
    'risks', 'risky', 'risps', 'risus', 'rites', 'ritts', 'ritzy', 'rival', 'rivas', 'rived',
    'rivel', 'riven', 'river', 'rives', 'rivet', 'rivos', 'riyad', 'riyal', 'roach', 'roads',
    'roams', 'roans', 'roars', 'roary', 'roast', 'roate', 'robed', 'robes', 'robin', 'roble',
    'robot', 'rocks', 'rocky', 'roded', 'rodeo', 'rodes', 'roger', 'rogue', 'rohan', 'rohun',
    'roids', 'roils', 'roily', 'roins', 'roist', 'rojak', 'rojis', 'roked', 'roker', 'rokes',
    'rolag', 'roles', 'rolfs', 'rolls', 'romal', 'roman', 'romeo', 'romps', 'ronde', 'rondo',
    'roneo', 'rones', 'ronin', 'ronne', 'ronts', 'roods', 'roofs', 'roofy', 'rooks', 'rooky',
    'rooms', 'roomy', 'roons', 'roops', 'roosa', 'roose', 'roost', 'roots', 'rooty', 'roped',
    'roper', 'ropes', 'ropey', 'roque', 'roral', 'rores', 'roric', 'rorid', 'rorie', 'rorts',
    'rorty', 'rosed', 'roses', 'roset', 'roshi', 'rosin', 'rosit', 'rosts', 'rotal', 'rotan',
    'rotas', 'rotch', 'roted', 'rotes', 'rotis', 'rotls', 'roton', 'rotor', 'rotos', 'rotte',
    'rotts', 'rouen', 'roues', 'rouge', 'rough', 'rouks', 'roule', 'rouls', 'roums', 'round',
    'roups', 'roupy', 'rouse', 'roust', 'route', 'routh', 'routs', 'roved', 'roven', 'rover',
    'roves', 'rowan', 'rowdy', 'rowed', 'rowel', 'rowen', 'rower', 'rownd', 'rowth', 'rowts',
    'royal', 'royne', 'royst', 'rozet', 'rozit', 'ruana', 'rubai', 'rubby', 'rubel', 'rubes',
    'rubin', 'ruble', 'rubli', 'rubus', 'ruche', 'rucks', 'rudas', 'rudds', 'ruddy', 'ruder',
    'rudes', 'rudie', 'rueda', 'ruers', 'ruffe', 'ruffs', 'rugae', 'rugal', 'rugby', 'ruggy',
    'ruing', 'ruins', 'rukhs', 'ruled', 'ruler', 'rules', 'rumal', 'rumba', 'rumbo', 'rumen',
    'rumes', 'rumly', 'rumor', 'rumpo', 'rumps', 'rumpy', 'runas', 'runch', 'runds', 'runed',
    'runes', 'rungs', 'runic', 'runny', 'runts', 'runty', 'rupee', 'rupiah', 'rural', 'rurus',
    'rusas', 'ruses', 'rushy', 'rusks', 'rusky', 'russe', 'rusts', 'rusty', 'ruths', 'rutin',
    'rutty', 'ryals', 'rybat', 'ryked', 'rykes', 'rymus', 'rynch', 'rynes', 'ryots', 'ryper',
    'rifle',
    
    // S words
    'sadly', 'safer', 'saint', 'salad', 'sales', 'salon', 'sauce', 'saved', 'saves', 'scale',
    'scare', 'scene', 'scent', 'scope', 'score', 'scout', 'screw', 'seats', 'seeds', 'seems',
    'sells', 'sense', 'serve', 'seven', 'shade', 'shake', 'shame', 'shape', 'share', 'shark',
    'sharp', 'sheet', 'shelf', 'shell', 'shine', 'ships', 'shirt', 'shock', 'shoes', 'shoot',
    'shops', 'shore', 'short', 'shots', 'shown', 'shows', 'sides', 'sight', 'signs', 'silly',
    'since', 'sinks', 'sites', 'sizes', 'skill', 'sleep', 'slice', 'slide', 'slope', 'slow',
    'small', 'smart', 'smile', 'smoke', 'snake', 'snaps', 'snow', 'sober', 'socal', 'socks',
    'solar', 'solid', 'solve', 'songs', 'sorry', 'sorts', 'souls', 'sound', 'soup', 'south',
    'space', 'spare', 'speak', 'speed', 'spell', 'spend', 'spent', 'spine', 'spite', 'split',
    'spoke', 'sport', 'spots', 'spray', 'stack', 'staff', 'stage', 'stake', 'stamp', 'stand',
    'stars', 'start', 'state', 'stays', 'steal', 'steam', 'steel', 'steps', 'stick', 'still',
    'stock', 'stone', 'stood', 'store', 'storm', 'story', 'strap', 'strip', 'stuck', 'study',
    'stuff', 'style', 'sugar', 'super', 'sweet', 'swift', 'swing', 'swiss',
    
    // T words
    'table', 'tails', 'takes', 'tales', 'talks', 'tanks', 'tapes', 'tasks', 'taste', 'taxes',
    'teach', 'teams', 'tears', 'teens', 'teeth', 'tells', 'tempo', 'tends', 'terms', 'tests',
    'thank', 'theft', 'their', 'theme', 'there', 'these', 'thick', 'thing', 'think', 'third',
    'those', 'three', 'threw', 'throw', 'thumb', 'tiger', 'tight', 'tiles', 'timer', 'times',
    'tired', 'title', 'toast', 'today', 'token', 'told', 'tools', 'tooth', 'topic', 'total',
    'touch', 'tough', 'tours', 'tower', 'towns', 'track', 'trade', 'trail', 'train', 'treat',
    'trees', 'trend', 'trial', 'tribe', 'trick', 'tried', 'tries', 'trips', 'truck', 'truly',
    'trunk', 'trust', 'truth', 'tubes', 'tulip', 'turns', 'twice', 'twins', 'twist', 'typed',
    'types',
    
    // U words
    'ultra', 'uncle', 'under', 'unfed', 'union', 'units', 'unity', 'until', 'upper', 'urban',
    'urged', 'usage', 'users', 'using', 'usual',
    
    // V words
    'valid', 'value', 'venue', 'verb', 'verse', 'video', 'views', 'virus', 'visit', 'vital',
    'vocal', 'voice', 'votes', 'vowel',
    
    // W words
    'wages', 'waist', 'waits', 'wake', 'walks', 'walls', 'wants', 'wards', 'warms', 'warns',
    'waste', 'watch', 'water', 'waves', 'weary', 'weeks', 'weird', 'wells', 'wheel', 'where',
    'which', 'while', 'white', 'whole', 'whose', 'wider', 'width', 'winds', 'wines', 'wings',
    'winks', 'wiped', 'wipes', 'wired', 'wires', 'witch', 'woman', 'women', 'words', 'works',
    'world', 'worry', 'worse', 'worst', 'worth', 'would', 'write', 'wrong', 'wrote',
    
    // X, Y, Z words
    'yacht', 'yards', 'years', 'yield', 'young', 'yours', 'youth', 'zones', 'zooms',
    
    // Additional valid guesses (technical terms and variants)
    'aahed', 'aalii', 'aargh', 'abaca', 'abaci', 'aback', 'abaft', 'abaka', 'abamp', 'abase',
    'abash', 'abate', 'abbey', 'abbot', 'abeam', 'abele', 'abers', 'abets', 'abhor', 'abide',
    'abled', 'abler', 'ables', 'abmho', 'abode', 'abohm', 'aboil', 'aboma', 'aboon', 'abort',
    
    // Technical and borrowed terms
    'adobe', 'adobo', 'adown', 'adoze', 'adsum', 'aduki', 'adunc', 'adust', 'advew', 'adyta',
    'adzed', 'adzes', 'aecia', 'aedes', 'aegis', 'aeons', 'aeros', 'aesir', 'afald', 'afar',
    'afars', 'afear', 'affix', 'afire', 'aflaj', 'afoot', 'afore', 'afoul', 'afrit', 'afros',
    
    // Scientific and medical terms
    'agama', 'agape', 'agars', 'agast', 'agate', 'agave', 'agaze', 'agene', 'agers', 'agger',
    'aggie', 'aggri', 'aggro', 'aghas', 'agila', 'agios', 'agism', 'agist', 'agita', 'aglet',
    'agley', 'agloo', 'aglow', 'aglus', 'agmas', 'agmie', 'agoge', 'agone', 'agons', 'agony',
    
    // More everyday words
    'early', 'earth', 'easel', 'eaten', 'eater', 'ebbed', 'ebony', 'ebook', 'eclat', 'edema',
    'edged', 'edges', 'edict', 'edify', 'edile', 'edits', 'educe', 'eerie', 'egads', 'egers',
    'egged', 'egger', 'egret', 'eider', 'eidos', 'eight', 'eikon', 'eisel', 'eject', 'eking',
    'elbow', 'elder', 'elect', 'elegy', 'elfin', 'elide', 'elite', 'elope', 'elude', 'elver',
    'elves', 'email', 'embed', 'ember', 'emcee', 'emeer', 'emend', 'emery', 'emeus', 'emirs',
    'emits', 'emmer', 'emmet', 'emoji', 'emong', 'emote', 'empty', 'emyde', 'enact', 'ender',
    'endow', 'endue', 'enema', 'enemy', 'enjoy', 'ennui', 'enoki', 'enrol', 'ensue', 'enter',
    'entry', 'envoy', 'enzym', 'eosin', 'epact', 'epees', 'ephah', 'ephas', 'epics', 'epoch',
    'epode', 'epoxy', 'equal', 'equip', 'erase', 'erect', 'ergot', 'erhus', 'erica', 'ering',
    'erned', 'ernes', 'erode', 'error', 'eruct', 'ervil', 'escar', 'escot', 'esile', 'eskar',
    'esker', 'esnes', 'essay', 'ester', 'estoc', 'estop', 'estro', 'etage', 'etape', 'etats',
    'ether', 'ethic', 'ethos', 'ethyl', 'etnas', 'ettin', 'ettle', 'etude', 'etwee', 'etyma',
    'eucre', 'euge', 'euked', 'euks', 'euros', 'evert', 'every', 'evets', 'evhoe', 'evict',
    'evils', 'evite', 'evoe', 'ewers', 'exact', 'exalt', 'exams', 'exarc', 'excel', 'exeat',
    'exec', 'execs', 'exede', 'exeem', 'exeme', 'exer', 'exes', 'exfil', 'exhie', 'exies',
    'exile', 'exine', 'exist', 'exits', 'exode', 'exome', 'exon', 'exons', 'expat', 'expel',
    'expos', 'expy', 'exsec', 'extol', 'extra', 'exude', 'exuls', 'exuma', 'exurb', 'eyass',
    'eyers', 'eying', 'eyots', 'eyras', 'eyres', 'eyrie', 'ezine',
    
    // Australian flora/fauna terms
    'billy', 'bonza', 'booze', 'bugle', 'bunya', 'chook', 'corgi', 'creek', 'dingo', 'dryer',
    'esky', 'fibro', 'footy', 'gecko', 'goose', 'gumby', 'heaps', 'hogan', 'jacky', 'jelly',
    'kelly', 'koala', 'larks', 'lolly', 'mucko', 'nerdy', 'ocker', 'party', 'polly', 'prawn',
    'quoll', 'ripper', 'scrub', 'seppo', 'shell', 'snaky', 'swamp', 'tinny', 'tucka', 'waddy',
    'wowee', 'yabby'
];

// Word definitions for educational value
const WORD_DEFINITIONS = {
    'about': 'Concerning; in connection with',
    'abuse': 'To treat with cruelty or violence',
    'actor': 'A person who acts in plays or films',
    'adopt': 'To take in and raise as one\'s own child',
    'adult': 'A fully grown person',
    'agree': 'To have the same opinion',
    'ahead': 'In front; in advance',
    'alarm': 'A warning sound or device',
    'alert': 'Quick to notice danger',
    'alive': 'Living; not dead',
    'allow': 'To give permission for',
    'alone': 'Without others; by oneself',
    'along': 'In company with',
    'alter': 'To change or modify',
    'among': 'In the midst of',
    'anger': 'A strong feeling of displeasure',
    'angry': 'Feeling or showing anger',
    'apple': 'A round fruit with red or green skin',
    'apply': 'To make a formal request',
    'argue': 'To give reasons for or against',
    'arise': 'To get up; to come into being',
    'array': 'An impressive display or arrangement',
    'arrow': 'A pointed projectile shot from a bow',
    'aside': 'To one side; apart',
    'asset': 'A valuable thing or quality',
    'atlas': 'A book of maps',
    'audio': 'Sound, especially recorded sound',
    'audit': 'An official inspection of accounts',
    'avoid': 'To keep away from',
    'awake': 'Not asleep; alert',
    'award': 'To give as a prize or reward',
    'aware': 'Having knowledge of something',
    'badge': 'A distinctive emblem worn as a sign',
    'badly': 'In a poor or inadequate way',
    'baker': 'A person who bakes bread and cakes',
    'basic': 'Fundamental; essential',
    'batch': 'A quantity produced at one time',
    'beach': 'A sandy or pebbly shore',
    'beard': 'Hair growing on a man\'s chin',
    'beast': 'A large animal',
    'being': 'Existence; a living creature',
    'belly': 'The stomach area',
    'below': 'At a lower level than',
    'bench': 'A long seat for several people',
    'billy': 'Australian: a metal pot for boiling water over a campfire',
    'birth': 'The emergence of a baby from the womb',
    'black': 'The darkest colour',
    'blade': 'The flat cutting edge of a knife',
    'blame': 'To hold responsible for a fault',
    'blank': 'Empty; containing nothing',
    'blast': 'A strong gust of wind or air',
    'blaze': 'A bright flame or fire',
    'bleak': 'Cold and forbidding',
    'blend': 'To mix smoothly together',
    'bless': 'To ask for divine favour upon',
    'blind': 'Unable to see',
    'block': 'A solid piece of material',
    'blood': 'The red liquid that flows in veins',
    'bloom': 'A flower; to produce flowers',
    'blown': 'Past participle of blow',
    'blues': 'A style of music; feelings of sadness',
    'bluff': 'A high steep cliff',
    'blunt': 'Having a dull edge; direct in speech',
    'blush': 'To become red in the face',
    'board': 'A flat piece of wood or other material',
    'boast': 'To talk proudly about oneself',
    'bobby': 'British: a police officer',
    'bogan': 'Australian: an uncouth or unsophisticated person',
    'bonza': 'Australian: excellent; first-rate',
    'boost': 'To help increase or improve',
    'booth': 'A small enclosed area',
    'booze': 'Australian: alcoholic drink',
    'bound': 'Certain to happen; tied up',
    'boxer': 'A person who fights in boxing matches',
    'brain': 'The organ inside the skull',
    'brake': 'A device for slowing or stopping',
    'brand': 'A type of product made by a company',
    'brass': 'A yellow metal; senior officials',
    'brave': 'Ready to face danger',
    'bread': 'Food made from flour and water',
    'break': 'To separate into pieces',
    'breed': 'To produce offspring',
    'bride': 'A woman on her wedding day',
    'brief': 'Lasting for a short time',
    'bring': 'To carry or escort to a place',
    'brink': 'The edge of a steep place',
    'broad': 'Wide; extensive',
    'broke': 'Having no money',
    'brook': 'A small stream',
    'brown': 'A colour like that of wood',
    'brush': 'An implement with bristles',
    'buddy': 'A close friend',
    'build': 'To construct',
    'built': 'Past tense of build',
    'bunch': 'A number of things grouped together',
    'bunny': 'A rabbit',
    'burnt': 'Past tense of burn',
    'burst': 'To break open suddenly',
    'buyer': 'A person who purchases things',
    'chook': 'Australian: a chicken',
    'cooee': 'Australian: a call used to attract attention',
    'cuppa': 'Australian: a cup of tea or coffee',
    'dingo': 'Australian: a wild dog native to Australia',
    'dryer': 'A machine for drying things (Australian spelling)',
    'dunny': 'Australian: an outdoor toilet',
    'esky': 'Australian: a portable cooler box',
    'footy': 'Australian: football (Australian Rules)',
    'garbo': 'Australian: a garbage collector',
    'giddy': 'Having a spinning sensation',
    'heaps': 'Australian: a large amount; very much',
    'jacky': 'Australian: a kookaburra',
    'kelly': 'Australian: an axe',
    'koala': 'Australian: a marsupial native to Australia',
    'larks': 'Fun activities; small songbirds',
    'lolly': 'Australian: a sweet or candy',
    'mucko': 'Australian: a person who mucks out stables',
    'nerdy': 'Studious but lacking social skills',
    'ocker': 'Australian: a stereotypical uncultivated Australian',
    'polly': 'Australian: a politician',
    'prawn': 'A marine crustacean',
    'quoll': 'Australian: a carnivorous marsupial',
    'ridge': 'A long narrow hilltop, mountain range, or watershed',
    'rifle': 'A firearm with a long barrel; to search through something',
    'right': 'Correct; opposite of left; a moral or legal entitlement',  
    'ripper': 'Australian: something excellent',
    'scrub': 'Vegetation in dry areas; to clean vigorously',
    'seppo': 'Australian: an American (rhyming slang)',
    'sheila': 'Australian: a woman',
    'snaky': 'Bad-tempered; containing snakes',
    'swamp': 'An area of waterlogged ground',
    'tinny': 'Australian: a can of beer; a small aluminium boat',
    'tucker': 'Australian: food',
    'waddy': 'Australian: a wooden war club',
    'wowee': 'Australian: an exclamation of surprise',
    'yabby': 'Australian: a small freshwater crayfish',
    'yakka': 'Australian: work, especially hard physical work'
};

// Function to get today's word
function getTodaysWord() {
    const today = new Date();
    // Use Australian Eastern Time
    const aest = new Date(today.toLocaleString("en-US", {timeZone: "Australia/Sydney"}));
    const daysSinceEpoch = Math.floor(aest.getTime() / (1000 * 60 * 60 * 24));
    const wordIndex = daysSinceEpoch % ANSWER_WORDS.length;
    return ANSWER_WORDS[wordIndex].toUpperCase();
}

// Function to check if a word is valid
function isValidWord(word) {
    return VALID_WORDS.includes(word.toLowerCase());
}

// Function to get word definition
function getWordDefinition(word) {
    return WORD_DEFINITIONS[word.toLowerCase()] || 'A legitimate word in Australian English.';
}

// Function to get time until next word
function getTimeUntilNextWord() {
    const now = new Date();
    const tomorrow = new Date(now);
    tomorrow.setHours(24, 0, 0, 0); // Next midnight
    
    const diff = tomorrow.getTime() - now.getTime();
    const hours = Math.floor(diff / (1000 * 60 * 60));
    const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
    const seconds = Math.floor((diff % (1000 * 60)) / 1000);
    
    return {
        hours: hours.toString().padStart(2, '0'),
        minutes: minutes.toString().padStart(2, '0'),
        seconds: seconds.toString().padStart(2, '0'),
        total: diff
    };
}